### ISSUE TITLE
[FEATURE REQ] Spring Cloud Azure Feature issue template

### ISSUE THREAD

**Issue by chenrujun** [chenrujun/spring-cloud-azure-feature-workflow#1]
### Context

1. [Key Vault](https://learn.microsoft.com/en-us/azure/key-vault/general/overview) provides secure storage of generic secrets, such as passwords and database connection strings.
2. **Spring Framework** provides [PropertySource Abstraction](https://docs.spring.io/spring-framework/docs/5.3.9/reference/html/core.html#beans-property-source-abstraction). A **PropertySource** is a simple abstraction over any source of key-value pairs. 
3. Maybe we (**Spring Cloud Azure** team) can release a library which provides a **PropertySource** that can retrieve secrets from **Key Vault**. This feature can help customer to get secret from **Key Vault** in their application much easier.

### Goal

 - Investigate whether we can use PropertySource to help customer easier to get secrets from KeyVault.
 - Implement this feature if possible.

### Solution

 - [ ] 1. Feature investigation.
 - [ ] 2. Write feature spec. 
 - [ ] 3. Feature spec review. 
 - [ ] 4. Implementation review. 
 - [ ] 5. Feature implementation. 
 - [ ] 6. Check the feature.

### Related members

 - Feature owner: @chenrujun
 - Implementation reviewer: @saragluna
 - Feature checker: @backwind1233
 - EM: @stliu

**Comment by chenrujun** [comment]
### 1. Feature investigation.

As described in the issue description. We can provide this feature. Here is the link to POC: [link to poc](.).

**Comment by chenrujun** [comment]
### 2. Write feature spec.

Customer can use this feature by these steps:

1. Add dependency
    ```xml
      <dependencies>
        <dependency>
          <groupId>com.azure.spring</groupId>
          <artifactId>spring-cloud-azure-starter-keyvault-secrets</artifactId>
        </dependency>
      </dependencies>
    ```
2. Create Java code
    ```yaml
    spring:
      cloud:
        azure:
          keyvault:
            secret:
              property-source-enabled: true
              property-sources:
                - name: key-vault-property-source-1
                  endpoint: ${ENDPOINT_1}
                - name: key-vault-property-source-2
                  endpoint: ${ENDPOINT_2}
    ```
3. Write Java codd
    ```java
    @SpringBootApplication
    public class PropertySourceApplication implements CommandLineRunner {
    
        @Value("${sampleProperty1}")
        private String sampleProperty1;
        @Value("${sampleProperty2}")
        private String sampleProperty2;
        @Value("${samplePropertyInMultipleKeyVault}")
        private String samplePropertyInMultipleKeyVault;
    
        public static void main(String[] args) {
            SpringApplication.run(PropertySourceApplication.class, args);
        }
    
        public void run(String[] args) {
            System.out.println("sampleProperty1: " + sampleProperty1);
            System.out.println("sampleProperty2: " + sampleProperty2);
            System.out.println("samplePropertyInMultipleKeyVault: " + samplePropertyInMultipleKeyVault);
        }
    
    }
    ```
4. Run the application, then it can get the secrets from Key Vault.
